apiVersion: v1
kind: Service
metadata:
  name: bookshelf-app-service
  annotations:
    cloud.google.com/load-balancer-type: "External" # Enable external GCP load balancer
spec:
  type: LoadBalancer
  selector:
    app: bookshelf-app # Match the label of your deployment pods
  ports:
    - protocol: TCP
      port: 80 # Expose port 80 externally
      targetPort: 80 # Application container listens on port 80
